### ISSUE TITLE
Installing from Community plugins within Obsidian fails

### ISSUE THREAD

**Issue by MSBack** [Sekund/sekund-plugin-react#24]
I am unable to install the latest release from within Obsidian. I reproduced this on a clean vault. Uninstalling the previous version first did not help, so now I have no version of Sekund installed.

**Comment by MSBack** [comment]
The error log in the console was as follows:
```
app.js:1 Obsidian Developer Console
app.js:1 Error: Request failed, status 404
    at YN (app.js:1:1505508)
    at app.js:1:1506152
    at app.js:1:235084
    at Object.next (app.js:1:235189)
    at s (app.js:1:233928)
(anonymous) @ app.js:1
app.js:1 Error: Request failed, status 404
    at YN (app.js:1:1505508)
    at app.js:1:1506152
    at app.js:1:235084
    at Object.next (app.js:1:235189)
    at s (app.js:1:233928)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
t.installPlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
s @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
L @ app.js:1
(anonymous) @ app.js:1
```

**Comment by ckemmler** [comment]
working on it... thanks!
I sometimes forget that `npm run build` doesn't produce the same output as `npm run dev`...

**Comment by ckemmler** [comment]
fixed
